version: '2'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon app.js
    environment:
      NODE_ENV: development
    env_file: .env
    ports:
      - '30002:3000'
    volumes:
      - .:/home/app/bot
      - /home/app/bot/node_modules
