version: '2'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file: env_file
    ports:
      - '30002:3000'
    volumes:
      - .:/home/app/bot
      - /home/app/bot/node_modules
